### ISSUE TITLE
enstaka.py krashar vid betygsättning i kursen cprog20

### ISSUE THREAD

**Issue by kallipygos** [pola/betygsrapportering#1]
´´´
share-01$ ./enstaka.py cprog20
resultat för:
	DD1388 cprog20 VT20-1 Programsystemkonstruktion med C++

sök efter en student:
>> philip
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./enstaka.py", line 42, in thread_retrieve_results_in_course
    student.get_results(course)
  File "/afs/kth.se/home/l/i/linek/asse/canvasrapportering/canvas.py", line 116, in get_results
    assignment = next(x for x in course.get_assignments() if x.id == submission['assignment_id'])
StopIteration
´´´

**Comment by kallipygos** [comment]
Nu fungerar det att söka student och välja uppgift. Kraschen kommer först vid betygsättning.


Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./enstaka.py", line 42, in thread_retrieve_results_in_course
    student.get_results(course)
  File "/afs/kth.se/home/l/i/linek/asse/canvasrapportering/canvas.py", line 116, in get_results
    assignment = next(x for x in course.get_assignments() if x.id == submission['assignment_id'])
StopIteration
